// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pynytoroxsqvfxybjeft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bnl0b3JveHNxdmZ4eWJqZWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjIwMjQsImV4cCI6MjA1ODUzODAyNH0.favQUuv9yeE3Xx-IxM6Hk5NHSqRf2Lb4DpA8cnbN9qQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);